image:
  file: Dockerfile.gitpod

tasks:
- name: configure build
  init: >
    mkdir -p build   &&
    cmake -B build . &&
    gp sync-done build-prepare
- name:    test
  init:    gp sync-await build-prepare
  command: ninja -C build tests
- name:    run
  init:    gp sync-await build-prepare
  command: ninja -C build run
- name:    debug
  init:    gp sync-await build-prepare
  command: ninja -C build debug
