# vim: ft=make

src_dir := $(dir $(realpath $(firstword $(MAKEFILE_LIST))))

all: libc.a crt1.o crti.o crtn.o

libc.a: $(src_dir)../newlib/build/Makefile
	+ make -C $(src_dir)../newlib/build
	+ make -C $(src_dir)../newlib/build install
	cp -r $(src_dir)../../sysroot/x86_64-lf_os-elf/* $(src_dir)../../sysroot
	rm -rf $(src_dir)../../sysroot/x86_64-lf_os-elf

crti.o: $(src_dir)lib/crti.S
	clang -g -flto -c $< -o $@

crtn.o: $(src_dir)lib/crtn.S
	clang -g -flto -c $< -o $@

crt1.o: $(src_dir)lib/crt1.S
	clang -g -flto -c $< -o $@

$(src_dir)../newlib/build:
	mkdir -p $@

$(src_dir)../newlib/build/Makefile: $(src_dir)../newlib/build crti.o crtn.o
	cd $(src_dir)../newlib/build && \
	CC_FOR_TARGET=clang \
	LD_FOR_TARGET=ld.lld  \
	CXX_FOR_TARGET=clang++ \
	AR_FOR_TARGET=llvm-ar-9 \
	AS_FOR_TARGET=clang \
	RANLIB_FOR_TARGET=llvm-ranlib-9 \
	READELF_FOR_TARGET=llvm-readelf-9 \
	OBJCOPY_FOR_TARGET=llvm-objcopy-9 \
	OBJDUMP_FOR_TARGET=llvm-objdump-9 \
	STRIP_FOR_TARGET=llvm-strip-9 \
	CFLAGS_FOR_TARGET="$(CFLAGS) -flto -DHAVE_INITFINI_ARRAY -D__GLIBC_USE\(...\)=0 $(OPTIMIZATION) -fuse-init-array" \
	../configure --target x86_64-lf_os-elf --disable-multilib --prefix $(src_dir)../../sysroot

clean:
	rm -rf $(src_dir)../newlib/build
	rm -f crti.o crtn.o crt1.o

.PHONY: clean
