# vim: ft=make

src_dir := $(dir $(realpath $(firstword $(MAKEFILE_LIST))))

all: clang

../tmp/clang-build:
	mkdir -p $@

../tmp/clang-build/Makefile: ../tmp/clang-build
	cd ../tmp/clang-build && \
	cmake -DLLVM_ENABLE_PROJECTS="clang;lld" \
		  -DLLVM_DEFAULT_TARGET_TRIPLE=x86_64-pc-lf_os \
		  -DLLVM_TARGETS_TO_BUILD=X86 \
		  -DCMAKE_INSTALL_PREFIX=$(LFOS_SYSROOT)/ \
		  -DCMAKE_BUILD_TYPE=Release \
		  -DCMAKE_C_COMPILER=clang \
		  -DCMAKE_CXX_COMPILER=clang++ \
		  -DLLVM_ENABLE_LLD=On \
		  -DLLVM_CCACHE_BUILD=On \
		  -DLLVM_BUILD_TOOLS=On \
		  -DLLVM_BUILD_UTILS=Off \
		  -DLLVM_BUILD_RUNTIMES=Off \
		  -DLLVM_BUILD_RUNTIME=Off \
		  $(src_dir)../llvm/llvm

clang: ../tmp/clang-build/Makefile
	+ make -C ../tmp/clang-build install

clean:
