# vim: set ft=perl
requires 'App::Cmd'             => '0.333';
requires 'Template::Toolkit'    => '3.009';
requires 'Regexp::Grammars'     => '1.057';
requires 'Test2::Suite'         => '0.000140';
requires 'Mouse'                => 'v2.5.10';
requires 'MouseX::NativeTraits' => '1.09';
requires 'YAML::XS'             => '0.83';
