cmake_minimum_required(VERSION 3.10)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(LLVM_ENABLE_RUNTIMES "compiler-rt;libcxx;libcxxabi;libunwind" CACHE STRING "LLVM runtimes to build")
set(CMAKE_INSTALL_PREFIX "${lf_os_sysroot}" CACHE STRING "Where to install the runtime libraries" FORCE)

set(COMPILER_RT_ENABLE_SHARED OFF)
set(LIBCXX_ENABLE_SHARED OFF)
set(LIBCXXABI_ENABLE_SHARED OFF)
set(LIBUNWIND_ENABLE_SHARED OFF)

set(LIBUNWIND_ENABLE_THREADS OFF)

set(COMPILER_RT_DEFAULT_TARGET_ONLY ON)
set(COMPILER_RT_USE_LIBCXX ON)
set(COMPILER_RT_CRT_USE_EH_FRAME_REGISTRY OFF)
set(COMPILER_RT_EXCLUDE_ATOMIC_BUILTIN OFF)
set(COMPILER_RT_BUILD_ORC OFF)

set(LIBCXX_ENABLE_THREADS ON)
set(LIBCXX_ENABLE_MONOTONIC_CLOCK ON)
set(LIBCXX_ENABLE_FILESYSTEM ON)
set(LIBCXX_ENABLE_STATIC_ABI_LIBRARY ON)
set(LIBCXX_ENABLE_ABI_LINKER_SCRIPT OFF)

set(LIBCXX_USE_COMPILER_RT ON)

set(LIBCXX_CXX_ABI "libcxxabi")
set(LIBCXX_CXX_STATIC_ABI_LIBRARY "c++abi")

set(LIBCXX_INCLUDE_TESTS OFF)
set(LIBCXXABI_INCLUDE_TESTS OFF)

set(LIBCXXABI_ENABLE_THREADS OFF)
set(LIBCXXABI_USE_COMPILER_RT ON)

set(LIBCXXABI_USE_LLVM_UNWINDER ON)
set(LIBCXXABI_ENABLE_STATIC_UNWINDER ON)

set(LIBCXX_CXX_ABI_LIBRARY_PATH "${lf_os_sysroot}/lib")
set(LIBCXXABI_LIBCXX_INCLUDES "${lf_os_sysroot}/include/c++/v1")

add_subdirectory(src/llvm/runtimes)
